export const DEBOUNCE_ANIMATION_TIME_OUT = 500;
export const DEBOUNCE_ANIMATION_IN_TIME_OUT = 10;

export const DEBOUNCE_CONTACT_FORM_MESSAGE_TIMEOUT = 5000;

export const HIDDEN_TOAST_TIMEOUT = 5000;

export const REDIRECT_DELAY = 5000;

export const COPIED_TO_CLIPBOARD_TIMEOUT = 2000;

export const HERO_IMAGE_SET_INTERVAL = 5000;
export const HERO_IMAGE_TRANSITION_TIMEOUT = 300;